### ISSUE TITLE
npm publish the build

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana-aws-sdk#1]
everything should be an external dependency

**Comment by torkelo** [comment]
Question should the npm package be under the @grafana npm namespace (so @grafana/aws-sdk or @grafana/aws-shared)

**Comment by sunker** [comment]
Oh I did not see this issue. It's published under the grafana scope, using the name @grafana/grafana-aws-sdk, but that can be changed. What do you think?

**Comment by sunker** [comment]
fixed in #5
