### ISSUE TITLE
AWS Auth Type dropdown option loses Workspace IAM Role option

### ISSUE THREAD

**Issue by wbrowne** [grafana/grafana-aws-sdk#10]
I think this is the right place for this bug I found. Seems like the Workspace IAM Role is on there on first load, and is gone after that

![Kapture 2021-03-19 at 15 56 39](https://user-images.githubusercontent.com/1173299/111800490-4bb82f80-88cc-11eb-818e-d9cce6831174.gif)

**Comment by sunker** [comment]
@zoltanbedi fixed this in https://github.com/grafana/grafana-aws-sdk/pull/9
