### ISSUE TITLE
Update SigV4 Auth providers to use the same configuration as AWS data sources

### ISSUE THREAD

**Issue by robbierolin** [grafana/grafana-aws-sdk#11]
Currently the `Authentication Providers` for AWS data sources are configurable via ini settings (https://github.com/grafana/grafana/blob/v7.5.0/conf/defaults.ini#L516). However the authentication providers for the SigV4 auth module does not read from this configuration. This leads to an inconsistent experience.

![Screen Shot 2021-03-25 at 11 39 00 AM](https://user-images.githubusercontent.com/8867000/112526032-bea72780-8d5e-11eb-9c20-eccd93f7075f.png)
![Screen Shot 2021-03-25 at 11 39 12 AM](https://user-images.githubusercontent.com/8867000/112526050-c23aae80-8d5e-11eb-947a-9b763afe8e56.png)

**Comment by sunker** [comment]
Fixed
