### ISSUE TITLE
Update Plugins to stop relying on env variables

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana-aws-sdk#122]
After https://github.com/grafana/grafana-aws-sdk/pull/121/files is merged and released, we should update the plugins to not depend on env variables to support multitenancy. Note that this isn't just bumping the version to 0.23.0, they also should use `ReadAuthSettings` to get the auth settings for an instance and pass that along to `GetSession`(link a reference to doing that in cloudwatch once its merged)

- [ ] Athena
- [ ] Redshift
- [ ] Timestream 
- [ ] CloudWatch
- [ ] X-ray
- [ ] TwinMaker
- [ ] SiteWise
- [ ] OpenSearch

**Comment by idastambuk** [comment]
Closed as Done
