### ISSUE TITLE
Move grafana/grafana AWS metrics maps into this package

### ISSUE THREAD

**Issue by tristanburgess** [grafana/grafana-aws-sdk#135]
**Is your feature request related to a problem? Please describe.**
Discussed in Slack

**Describe the solution you'd like**
We would like to migrate the metrics map library currently in [`grafana/grafana`'s `tsdb` package](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/constants/metrics.go). Currently, users of the metrics map as is requires wholesale importing `grafana/grafana` as a Go package, which can cause false positive build failures from detecting Go vulnerabilities on other unrelated areas of that package.

**Comment by njvrzm** [comment]
Maybe wait til this open PR is merged: https://github.com/grafana/grafana/pull/88418

**Comment by iwysiu** [comment]
@tristanburgess Done, and released in [v0.26.1](https://github.com/grafana/grafana-aws-sdk/releases/tag/v0.26.1) of grafana-aws-sdk
