### ISSUE TITLE
Setup CI/CD for this repo

### ISSUE THREAD

**Issue by sunker** [grafana/grafana-aws-sdk#27]
Currently, the only way to publish to npm and our github registry is by running 
```
yarn build
yarn bundle 
npm publish  --access=public --scope=@grafana
```
This requires you to be logged into npm and to be part of the grafana org. Not sure exactly how, but I'd like these steps to be automated. See [this](https://github.com/grafana/eslint-config-grafana/pull/10) PR to get an idea of how this has been solved in other repos at grafana.

For the backend, we could possibly have a bot create new releases every time we merge to the main branch. This is still TBD. 

This should be done after this repo is split up in two. See [this](https://github.com/grafana/grafana-aws-sdk/issues/26) issue.

**Comment by andresmgot** [comment]
This was actually done with #30  and https://github.com/grafana/grafana-aws-sdk-react/pull/1
