### ISSUE TITLE
Explore Supporting Session Name

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana-aws-sdk#77]
It's possible to name sessions now: https://aws.amazon.com/blogs/security/easily-control-naming-individual-iam-role-sessions/

Users can name a session and set up a condition to only let a role be assumed for certain names (similar to an externalId). It would be nice if we could support this for users such as by adding another field in ConnectionsDetails or by letting users manually add it to a credentials file.

**Comment by katebrenner** [comment]
close as not planned
