### ISSUE TITLE
Opt-in Regions list is out of date

### ISSUE THREAD

**Issue by eunice98k** [grafana/grafana-aws-sdk#79]
The list of AWS Opt-in regions in [sessions.go](https://github.com/grafana/grafana-aws-sdk/blob/main/pkg/awsds/sessions.go) does not include the latest AWS Regions. This limits users ability to use the latest AWS regions. 
Please see the available region list [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html).

We will need to consume the new SDK version release in the plugin list below:

- [x] Athena https://github.com/grafana/athena-datasource/pull/234
- [x] Redshift: https://github.com/grafana/redshift-datasource/pull/222
- [x] Timestream: https://github.com/grafana/timestream-datasource/pull/233
- [x] CloudWatch: https://github.com/grafana/grafana/pull/67876
- [x] X-ray: https://github.com/grafana/x-ray-datasource/pull/185
- [x] TwinMaker: https://github.com/grafana/grafana-iot-twinmaker-app/pull/189
- [x] SiteWise :https://github.com/grafana/iot-sitewise-datasource/pull/181
- [x] OpenSearch: https://github.com/grafana/opensearch-datasource/pull/162

**Comment by eunice98k** [comment]
PR created: https://github.com/grafana/grafana-aws-sdk/pull/80

**Comment by fridgepoet** [comment]
For whoever picks this one up, see: https://raintank-corp.slack.com/archives/C01LVB0CYTW/p1681916301705699?thread_ts=1681836486.606569&cid=C01LVB0CYTW
