### ISSUE TITLE
Opt-in Regions list is out of date

### ISSUE THREAD

**Issue by Brandon-Kimberly** [grafana/grafana-aws-sdk#94]
The [list](https://github.com/grafana/grafana-aws-sdk/blob/main/pkg/awsds/sessions.go#L141) of AWS Opt-in regions in [sessions.go](https://github.com/grafana/grafana-aws-sdk/blob/main/pkg/awsds/sessions.go) does not include the latest AWS Regions. This limits users ability to use the latest AWS regions.
Please see the available region list [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html). It is missing `il-central-1`.

We will need to consume the new SDK version release in the plugin list below:

- [x] Athena
- [x] Redshift
- [x] Timestream
- [x] CloudWatch
- [x] X-ray
- [x] TwinMaker
- [x] SiteWise
- [x] OpenSearch

**Comment by reagankan** [comment]
Hey Team, are there any updates as to whether this will be worked on in the near-term?

AMG customers are waiting for a fix, thanks!
